{% set name = "siesta" %}
{% set version_base = "4.0" %}
{% set version = "4.0.2" %}
{% set md5 = "5f6d1c2ffb96c58bb45c5d76b6bb4bb2" %}
{% set sha256 = "bafbda19358f0c1dd39bb1253c92ee548791a1c0f648977051d2657216874f7e" %}

package:
  name: {{ name }}
  version: {{ version }}

source:
  fn: {{ name }}-{{ version }}.tar.gz
  url: https://launchpad.net/{{ name }}/{{ version_base }}/{{ version }}/+download/{{ name }}-{{ version }}.tar.gz
  md5: {{ md5 }}
  sha256: {{ sha256 }}
  patches:
    - 0000-version.F90.patch

# Default build version to be stepped with every new build!
{% set build = 5 %}

# Define build matrix for MPI vs. non-mpi
## ensure mpi is defined (needed for conda-smithy recipe-lint)
{% set mpi = mpi or 'nompi' %}
{% if mpi == 'nompi' %}
# prioritize nompi variant via build number
# this is 100 in the docs and should be changed to that
# for the next version bump
{% set build = build + 1000 %}
{% endif %}

build:
  number: {{ build }}
  skip: true  # [win]

  {% if mpi != 'nompi' %}
  {% set mpi_prefix = "mpi_" + mpi %}
  {% else %}
  {% set mpi_prefix = "nompi" %}
  {% endif %}
  string: "{{ mpi_prefix }}_h{{ PKG_HASH }}_{{ build }}"

  {% if mpi != 'nompi' %}
  run_exports:
    - {{ name }} * {{ mpi_prefix }}_*
  {% endif %}

requirements:
  build:
    - {{ compiler('fortran') }}
    - {{ compiler('c') }}
  host:
    - liblapack
    - {{ mpi }}  # [mpi != 'nompi']
    - netcdf-fortran
    - scalapack  # [mpi != 'nompi']
  run:
    - liblapack
    - {{ mpi }}  # [mpi != 'nompi']
    - netcdf-fortran
    - scalapack  # [mpi != 'nompi']

test:
  source_files:
    - Tests/**

about:
  home: https://launchpad.net/siesta/
  license: GPL-3
  license_family: GPL
  license_file: COPYING
  summary: A first-principles materials simulation code using DFT
  description: |
    SIESTA is both a method and its computer program implementation,
    to perform efficient electronic structure calculations and ab initio
    molecular dynamics simulations of molecules and solids. SIESTA's
    efficiency stems from the use of strictly localized basis sets and
    from the implementation of linear-scaling algorithms which can be
    applied to suitable systems. A very important feature of the code is
    that its accuracy and cost can be tuned in a wide range, from quick
    exploratory calculations to highly accurate simulations matching the
    quality of other approaches, such as plane-wave and all-electron methods.
  doc_url: https://launchpad.net/siesta/{{ version_base }}/{{ version }}/+download/siesta.pdf
  dev_url: https://launchpad.net/siesta/

extra:
  recipe-maintainers:
    - zerothi
    - albgar
