bot:
  abi_migration_branches:
  - main
  - v4.1.x
build_platform:
  osx_arm64: osx_64
conda_build:
  pkg_format: '2'
conda_forge_output_validation: true
test: native_and_emulated
github:
  branch_name: main
  tooling_branch_name: main
conda_build:
  pkg_format: '2'
test_on_native_only: true
