travis:
  secure:
    BINSTAR_TOKEN: arEB8stPRO77bUZ85SlS7GhmpNm72x93sY2wgMtfAdpqIgXudL8HnkkiuPC9n5IS9jHoUQsepjOn1Fm8yzGzDaRgR4dozhEKtceqQA0r0r7ckXTE5VwZxyINrZSz1Mwy8MBqjptCSd1z3C3wuVbv/L7DrauHY7N4/bhAAie7tjVnDnE5hUBveIdINbPt/mn8b8LAg5Xw37XVOSVyq4O2I1LZvfpiu1Qm3psxhKpGFTD4Q8TmpEAbDRnG5Wg8fHWn+dRvdM3Kth/akgMM5L40pDs3FrtMxDiWb+zGmPlNy7VAHqFdv0kBr89mmnDoA+8GRyYjLPwYH67t5RWJ8hiX3epJmisQWDB2wxVGYOZsUW1mAY7o1BWInIBhWtRYwSXHSNr28qm/Ydn4cK3hcXeNroj1e2VUGEW+yhTIQUGAGAo90GcQ0HLjOKyfGP1220TJDOmSICPpY9NOpB73QptdMK90O1hSu9pw0wKPVEN5BDQfz/uUiy8ItSg2/uz68wXjfIwaTD2UrDFsHr9vEp3T13sQQFVlmtyKw7sFO1zEIbjexWDzSdu3GeILpZHqcD+6QgF2KxLkXbQx4JMO24u110nqpZ8OucMxVb5NIPypdPF/WFGibI1LHHZP352KNcNLVA/iOyPWcrFZSdRK89i8oWu6DQsjM+aWsdYuWUkBKOk=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
