travis:
  secure:
    BINSTAR_TOKEN: buXxSocGqDK/SvjI6IkKtzD6rVuejW9fiPS/lrSMyJkkTBoKWKrImtv9gAqwVxVr6gdLCw83XWIl9paNbfGb7kbcAwxs1H4r4opLn2lyThLj4djOfVBF7Gzf39Y0oHCcQaKzvozB16gF9084IbaJ7BPzuzkvZf6zzWUowHVbkU2sWMgR6z8zB5gN4AbKoWdOQTyD9up9yENZnG3wcJrFALZmNN09l+fj9Ik1MHKrFEZ2ANANUbFIt8NLuKDi96f6lAaRlsZ4+z5meeaTkV0T81NoqYbB17eLAnICaGi3j8m3qZ2LX7ERWDnZ+mjNJEUfFScO4HylehwrFhXyDY2OT6JJVwD2qhXF5BHFG3haIjW8qhX3SpjwIYA5o1t8U+Y0bw6eZCS/7uUJYUHkqFaeBtqqsc8001UyjUFzBRHgp3d1wIVYzd9sNyF6QT8nArEMmjegjyUubfWfDu0An6GWHtRexm87D3pnqRjdPDIypj26yJvr0js3z0Jc23yGC2+bFJFQKpF1uRNScLM4b1sBp3tmO+TUF+ga82czw5q+EI92INb5f0Ohbxa2Nl9nDkc3oEwpGWyhi+TxRh35VuwqmcWB3IxF7sGjAMmRSh2ckwJqKSekItQHdsgICknRdDcxj2CZ1odHHwuZMU04s17ZruO5eyjpQYgNR0FOJVBOiXA=
appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
