# This file was generated automatically from conda-smithy. To update this configuration,
# update the conda-forge.yml and/or the recipe/meta.yaml.
# -*- mode: yaml -*-

jobs:
- job: linux
  pool:
    vmImage: ubuntu-16.04
  timeoutInMinutes: 360
  strategy:
    maxParallel: 8
    matrix:
      linux_blas_implblismpimpich:
        CONFIG: linux_blas_implblismpimpich
        UPLOAD_PACKAGES: True
      linux_blas_implblismpinompi:
        CONFIG: linux_blas_implblismpinompi
        UPLOAD_PACKAGES: True
      linux_blas_implblismpiopenmpi:
        CONFIG: linux_blas_implblismpiopenmpi
        UPLOAD_PACKAGES: True
      linux_blas_implmklmpimpich:
        CONFIG: linux_blas_implmklmpimpich
        UPLOAD_PACKAGES: True
      linux_blas_implmklmpinompi:
        CONFIG: linux_blas_implmklmpinompi
        UPLOAD_PACKAGES: True
      linux_blas_implmklmpiopenmpi:
        CONFIG: linux_blas_implmklmpiopenmpi
        UPLOAD_PACKAGES: True
      linux_blas_implopenblasmpimpich:
        CONFIG: linux_blas_implopenblasmpimpich
        UPLOAD_PACKAGES: True
      linux_blas_implopenblasmpinompi:
        CONFIG: linux_blas_implopenblasmpinompi
        UPLOAD_PACKAGES: True
      linux_blas_implopenblasmpiopenmpi:
        CONFIG: linux_blas_implopenblasmpiopenmpi
        UPLOAD_PACKAGES: True
  steps:
  - script: |
      sudo pip install --upgrade pip
      sudo pip install setuptools shyaml
    displayName: Install dependencies

  # configure qemu binfmt-misc running.  This allows us to run docker containers
  # embedded qemu-static
  - script: |
      docker run --rm --privileged multiarch/qemu-user-static:register --reset --credential yes
      ls /proc/sys/fs/binfmt_misc/
    condition: not(startsWith(variables['CONFIG'], 'linux_64'))
    displayName: Configure binfmt_misc

  - script: .azure-pipelines/run_docker_build.sh
    displayName: Run docker build
    env:
      BINSTAR_TOKEN: $(BINSTAR_TOKEN)