jobs:
- job: linux_64
  pool:
    vmImage: ubuntu-16.04
  timeoutInMinutes: 240
  strategy:
    maxParallel: 8
    matrix:
      linux_c_compilergccfortran_compilergfortranmpimpich:
        CONFIG: linux_c_compilergccfortran_compilergfortranmpimpich
      linux_c_compilergccfortran_compilergfortranmpiopenmpi:
        CONFIG: linux_c_compilergccfortran_compilergfortranmpiopenmpi
      linux_c_compilertoolchain_cfortran_compilertoolchain_fortmpimpich:
        CONFIG: linux_c_compilertoolchain_cfortran_compilertoolchain_fortmpimpich
      linux_c_compilertoolchain_cfortran_compilertoolchain_fortmpiopenmpi:
        CONFIG: linux_c_compilertoolchain_cfortran_compilertoolchain_fortmpiopenmpi
  steps:
  - script: |
      sudo pip install --upgrade pip
      sudo pip install setuptools shyaml
    displayName: Install dependencies

  - script: .azure-pipelines/run_docker_build.sh
    displayName: Run docker build